# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint-cli2/refs/heads/main/schema/markdownlint-cli2-config-schema.json
# config: https://github.com/DavidAnson/markdownlint-cli2#configuration

# config:
#   first-line-h1: false
#   no-duplicate-heading: false
ignores:
  - CHANGELOG.md
