[tools]
actionlint = "1"
gitleaks = "8"
python = "3.11"
"pipx:pre-commit-hooks" = "6"
"pipx:commitizen" = "4"
"ubi:huacnlee/autocorrect" = "2"
typos = "1"
prettier = "3.6"
tombi = "0.6"
yamllint = "1.37"
markdownlint-cli2 = "0.18"

[tools."ubi:editorconfig-checker/editorconfig-checker"]
version = "3"
matching = "editorconfig-checker"

[tools.'ubi:evilmartians/lefthook']
version = "1.13"
rename_exe = 'lefthook{% if os_family() == "windows" %}.exe{% endif %}'

[tools."ubi:mvdan/sh"]
version = "3"
rename_exe = 'shfmt{% if os_family() == "windows" %}.exe{% endif %}'

[tools."github:koalaman/shellcheck"]
version = "0.11"
platforms.windows-x64 = { asset_pattern = "shellcheck-v*.zip" }

[settings.pipx]
uvx = false
