[tools]
actionlint = "latest"
gitleaks = "latest"
lefthook = "1.11"
python = "3.11"
"pipx:pre-commit-hooks" = "5"
"pipx:commitizen" = "4"
"ubi:huacnlee/autocorrect" = "2.13"
typos = "1.31"
# editorconfig-checker-disable-next-line
# NOTE: [Confusion on official cli binary name #232](https://github.com/editorconfig-checker/editorconfig-checker/issues/232)
# 使用 editorconfig-checker 匹配 github release asset ，避免匹配了 ec 使用
# editorconfig-checker 作为 binname 找不到的问题
[tools."ubi:editorconfig-checker/editorconfig-checker"]
version = "3"
matching = "editorconfig-checker"
